name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run update-readme
        env:
          STEAM_API: ${{ secrets.STEAM_API }}
      - run: |
          git config user.name vgarmes
          git config user.email vgmestre@gmail.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README"
          git push origin main
